spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/E-LearningDB
    username: postgres
    password: 092000The
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true