spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SchoolDB
    username: postgres
    password: 092000The
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
